services:
  - type: web
    name: pokemon-card-api
    runtime: python
    rootDir: pokeca/backend
    plan: free
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt && python -m database.setup
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: CARGO_HOME
        value: /tmp/cargo
