services:
  - type: web
    name: pokemon-card-api
    runtime: python
    rootDir: pokeca/backend
    plan: free
    pythonVersion: 3.11.8
    buildCommand: |
      if [ -d pokeca/backend ]; then
        cd pokeca/backend
      fi
      pip install -r requirements.txt
      python database/setup.py
    startCommand: |
      if [ -d pokeca/backend ]; then
        cd pokeca/backend
      fi
      python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: CARGO_HOME
        value: /tmp/cargo
